services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Host=postgres;Port=5432;Database=demoapi;Username=postgres;Password=postgres
      - Database__Provider=PostgreSql
      - Authentication__Jwt__Authority=http://keycloak:8080/realms/template-realm
      - Authentication__Jwt__Audience=api-host
      - Authentication__Jwt__RequireHttpsMetadata=false
    depends_on:
      - postgres
      - keycloak

  postgres:
    image: postgres:18
    environment:
      - POSTGRES_DB=demoapi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:26.8
    command: start-dev
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    ports:
      - "8081:8080"
