services:
  mvc:
    build:
      context: ../../templates/neillans-mvc/content
      dockerfile: docker/Dockerfile
    ports:
      - "8090:8080"
    environment:
      - Authentication__Oidc__Authority=http://keycloak:8080/realms/template-realm
      - Authentication__Oidc__ClientId=mvc-host
      - Authentication__Oidc__ClientSecret=mvc-host-secret
    depends_on:
      - keycloak

  api:
    build:
      context: ../../templates/neillans-api/content
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - Database__Provider=PostgreSql
      - ConnectionStrings__Default=Host=postgres;Port=5432;Database=fullstack;Username=postgres;Password=postgres
      - Authentication__Jwt__Authority=http://keycloak:8080/realms/template-realm
      - Authentication__Jwt__Audience=api-host
      - Authentication__Jwt__RequireHttpsMetadata=false
    depends_on:
      - postgres
      - keycloak

  postgres:
    image: postgres:18
    environment:
      - POSTGRES_DB=fullstack
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:26.8
    command: start-dev
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    ports:
      - "8081:8080"

  spa:
    build:
      context: ../../templates/neillans-angular/content/angular-app
      dockerfile: docker/Dockerfile
    ports:
      - "4200:80"
