<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PackageType>Template</PackageType>
    <PackageId>Aneillans.Templates.Api</PackageId>
    <Version>1.0.0</Version>
    <Authors>Aneillans</Authors>
    <Description>Aneillans API project template with auth, swagger, docker, and tests.</Description>
    <PackageTags>dotnet-new;template;api;swagger;oidc;keycloak</PackageTags>
    <IncludeContentInPack>true</IncludeContentInPack>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <NoDefaultExcludes>true</NoDefaultExcludes>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="content\**\*" PackagePath="content" />
    <Content Include=".template.config\**\*" PackagePath=".template.config" />
  </ItemGroup>
</Project>
