<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PackageType>Template</PackageType>
    <PackageId>Aneillans.Templates.Angular</PackageId>
    <Version>1.0.0</Version>
    <Authors>Aneillans</Authors>
    <Description>Aneillans Angular SPA template with OIDC and Docker.</Description>
    <PackageTags>dotnet-new;template;angular;oidc;keycloak;docker</PackageTags>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <NoWarn>$(NoWarn);NU5128</NoWarn>
    <IncludeContentInPack>true</IncludeContentInPack>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <NoDefaultExcludes>true</NoDefaultExcludes>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="content\**\*" Exclude="content\angular-app\node_modules\**\*" PackagePath="content" />
    <Content Include=".template.config\**\*" PackagePath=".template.config" />
  </ItemGroup>
</Project>
